artifact_uri: file:///home/dumball/code/pytorch-scratch/ml-flow/0/a0dad522b0be4a509714be0a4ed77f94/artifacts
end_time: 1708959125575
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: a0dad522b0be4a509714be0a4ed77f94
run_name: loud-goat-247
run_uuid: a0dad522b0be4a509714be0a4ed77f94
source_name: ''
source_type: 4
source_version: ''
start_time: 1708959119932
status: 3
tags: []
user_id: dumball
